### ISSUE TITLE
[electron] Can't use electron out-of-the-box with sdk 36.

### ISSUE THREAD

**Issue by yungkittty** [expo/expo-electron-adapter#9]
## Description

I'm trying to setup expo with electron (SDK 36).

To do so, I've followed this [guide](https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/guides/using-electron.md).

Finally, I've tried to run `yarn expo-electron start`.

## Expected Behavior

It should start the electron app using the `AppEntry.js` (main field from package.json) or whatever pre-configured (index||app).(js||ts) from expo. This would ensure all the configuration of expo for web apps is also applied to electron and it would keep a universal entry point (if none special configuration).

## Observed Behavior

```
┏ Renderer -------------------

  Error: Cannot find entry file index.ts (or main.ts, or app.ts, or index.js, or main.js, or app.js)
      at computeEntryFile (/home/x/Clones/happew-boilerplate/node_modules/electron-webpack/src/main.ts:389:11)
      at WebpackConfigurator.configure (/home/x/Clones/happew-boilerplate/node_modules/electron-webpack/src/main.ts:222:29)
      at configure (/home/x/Clones/happew-boilerplate/node_modules/electron-webpack/src/main.ts:376:10)

┗ ----------------------------
```

I've looked-up the configuration of electron-webpack and it's this [function](https://github.com/electron-userland/electron-webpack/blob/master/packages/electron-webpack/src/main.ts#L379) that throw this error. From all the docs and examples provided by expo none talks about declarating a (index||app).(js||ts) file.

## Environment

```
Expo CLI 3.11.3 environment info:
    System:
      OS: Linux 4.15 elementary OS 5.1 Hera
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 13.5.0 - ~/.nvm/versions/node/v13.5.0/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v13.5.0/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v13.5.0/bin/npm
    npmPackages:
      @types/react: ~16.9.0 => 16.9.17 
      @types/react-native: ~0.60.23 => 0.60.25 
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.11.3
```

## Reproducible Demo

I've this error with this [repository](https://github.com/expo/examples/tree/master/with-electron) (expo/examples) which use the sdk 35.

**Comment by fangpenlin** [comment]
I encountered the same problem and I dug a bit to understand why it works on Windows / Mac but not Linux. So basically,

https://github.com/electron-userland/electron-webpack/blob/ca18b60daa172c8f0249f9bf4e89a2f76a1cbe44/packages/electron-webpack/src/main.ts#L381-L385

the electron-webpack main is trying to find `index`, `main` and `app` with any one of suffixes among `ts`, `js`, `tsx` and `jsx`. For Expo app, you got `App.tsx` in the renderer source folder `./` defined here

https://github.com/expo/expo-electron-adapter/blob/b9de1864183116d3332d651cdfa9575f54441585/src/Config.ts#L75

Under Windows or MacOS, as if the filesystem is using case insensitive filename filesystem, the `computeEntryFile` is gonna find `App.tsx` regardless it's not `app.tsx`. But for Linux, usually case sensitive filename filesystem is used, as a result, it cannot find the entry point for index file.

A simple solution by adding an empty index.js in renderer source folder could work, and it should be filtered out by this adapter here:

https://github.com/expo/expo-electron-adapter/blob/b9de1864183116d3332d651cdfa9575f54441585/src/Webpack.ts#L80-L85

**Comment by Simbaclaws** [comment]
Can't ```yarn expo-electron``` be altered to create a empty index.js file if it doesn't yet exist?

It really doesn't have to be that hard to implement a solution to this just to have support for linux out of the box....
It's embarrassingly easy to add to this project no?

**Comment by ollyde** [comment]
@Simbaclaws doesn't work for me, loads of issues when adding it to a blank expo project.
